name: Filesize Guard
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  filesize_guard:
    runs-on: ubuntu-latest
    steps:
      - name: Filesize Guard
        uses: chris-rutkowski/filesize-guard@v103
        # with:
        #   ignore_file: my_filesize_guard.ignore
